@startuml
actor Medico
participant Controller
participant UseCase
participant PatientRepo
participant MedicationRepo
participant AllergyRepo
participant PrescriptionRepo

Medico -> Controller : POST /prescriptions
Controller -> UseCase : execute()
UseCase -> PatientRepo : findById()
UseCase -> MedicationRepo : findById()
UseCase -> AllergyRepo : findActiveByPatientId()
UseCase -> PrescriptionRepo : save()
UseCase --> Controller : success
Controller --> Medico : 201 Created
@enduml
